name: WakaTime Dev Stats

on:
  schedule:
    # Runs automatically every midnight UTC
    - cron: '0 0 * * *'
  # Allows you to manually trigger the workflow from the Actions tab
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          TIME_RANGE: last_7_days
          SHOW_TIME: true
          SHOW_TOTAL: true
